dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "2.7"
env:
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=1.11
services:
  - memcached
  - redis
  - mysql
  - postgresql
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.1
    - python: "2.7"
      env: DJANGO_VERSION=2.2
    - python: "3.8"
      env: DJANGO_VERSION=1.11
    - python: "3.7"
      env: DJANGO_VERSION=1.11
    - python: "3.6"
      env: DJANGO_VERSION=1.11

install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install --upgrade setuptools wheel
  - mysql -e 'create database django_prometheus_1;'
script:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.7" ]]; then black --check django_prometheus/; fi
  - coverage run --source=django_prometheus setup.py test
  - python setup.py sdist bdist_wheel
  - cd django_prometheus/tests/end2end && PYTHONPATH=../../.. python manage.py test
after_success:
  - coveralls
before_deploy:
  - git checkout $TRAVIS_BRANCH
  - git fetch --unshallow
  - python update_version_from_git.py
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_existing: true
    # Testing with test pypi first
    server: https://test.pypi.org/legacy/ 
    user: asherf
    password:
      secure: w4oLPAzKlNkOaLyMlg+laZjQlCrV96aYM8nNn0XXvIGDrujlyCGOl9BWn039YL6alVf1siLP+FQHfwJmX1JCmqMgM5DdzV99sLvbgkcxL6u5OMotxKURGuboSPuDMFi7KWhbahP/iXtJQtVj1yzuhQs7kcb0B4qUi3mG0yIWJuiNDMzkAsiHN4YUFWprGAJ1PfaScYcyH6mrq/Q3SYcWkjOvf6gabANDZMd/PiVaGWsMleh3MnwfMKtIPgISQOkqg11RmolFz+mmzbFD6+OLlIl+RDEWnHZuDQ9PoaIJow4T02nTfsFxmZF0iEKjnGCc6NXtjum5JrtliK6Jxa8nLf+zuV0nhicRmF2OZlZcS74gGxETiwn1qZNHYfhkEhZa/VI8iKrZnBNVqnAygtFsH2KO8/r9FfWZFV72pLWjHB7zr6GFXGXfkx+W/+ALCms0nIkIyeeh7Fw8y2gsfyLPFfknURWFzidKQaFrdrBkzurUVm5tQUMrJVToClaDwXLZLiuJ4Fro2xxR/8NQ/qCChHPreZnZ7iW3+n9WKuFM6mKh8Es5ZZtMeMRk6jJubvVZQCpJgtBx07NGJ701niZT59ReVA3Y9EkvtpEDrqUK/NYeKeUXDwhghtyrlCZ9gpcjbqVMFzt01/dT4Jhfi1gEJzcuWLdUYh8T+guTWxf0Un8=
    on:
      branch:
      - master
